

import sys
import os
import time

import pyauto
from keyhac import *

"""
keyhac の設定ファイル

問題点
1. 特に致命的なものは確認していない
2. キーボードマクロの動作で time inversion のメッセージが出る
3. とりあえずオブジェクティブなコードにしたが、密結合なのでなんとかしたい
4. IME の設定とか無変換キーを使った設定とかあるので日本語でいいのではないか
"""

"""
動的なキーマップを制御するためのクラス
keymap.defineWindowKeymap(...) の引数 check_func を適当に設定することにより動的キーマップを実現する
本クラスは静的クラスである
本クラスは静的メンバ flag_window により動的なキーマップモードを保持している
"""



    
class KeymapConfig:
    """This class provide the function to set keymap as `set_keymap(keymap)`. 
    
    Notably, in this class, dynamic keymap is realized by `keymap.defineWindowKeymap(checkfunc = {function to get current mode})`.
    `{function to get current mode}` is provided by KeymapMode class. 
    Mode changes are fired by "key"s, which call functions `KeymapMode.set_xxx()` and `keymap.updateKeymap()`.
    """


    class KeymapMode:
        """This class stores the current keymap mode flags. 
        This class does not change status of `keymap` itself. 
        This class is static class. 
        """
        
        _LIMITED = 0
        _CURSOR = 1
        _CELESTE = 2
        _TEST = 3

        _mode=_LIMITED # keymap mode flag default is _LIMITED

        @classmethod
        def set_limited(cls):
            cls._mode = cls._LIMITED

        @classmethod
        def set_cursor(cls):
            cls._mode = cls._CURSOR

        @classmethod
        def set_celeste(cls):
            cls._mode = cls._CELESTE

        @classmethod
        def set_test(cls):
            cls._mode = cls._TEST
        

        @classmethod
        def is_limited(cls,dummy_window):
            return cls._mode == cls._LIMITED
        
        @classmethod
        def is_cursor(cls,dummy_window):
            return cls._mode == cls._CURSOR

        @classmethod
        def is_celeste(cls,dummy_window):
            return cls._mode == cls._CELESTE

        @classmethod
        def is_test(cls,dummy_window):
            return cls._mode == cls._TEST

    


    class KeymapsImpl:
        """This class defines the implementation for each keymap generated by `keymap.defineWindowKeymap(...)`.
        """

        @classmethod
        def _set_keymap_global(cls, keymap_global, keymap):
            """This function set settings of `keymap_global`. 
            - Mode-change
            - IME-ON/OFF
            - Oneshot Slash for escaping Modifyer

            Args:
                keymap_global (WindowKeymap): `WindowKeymap` instance generated by `keymap.defineWindowKeymap()`.
                keymap (Keymap): `Keymap` instance. This is necessary because `keymap_global` has the function to change keymap modes.
            """


            # Definitions of mode-change functions. 
            
            def set_keymap_limited():
                KeymapConfig.KeymapMode.set_limited()
                keymap.updateKeymap()

            def set_keymap_cursor():
                KeymapConfig.KeymapMode.set_cursor()
                keymap.updateKeymap()
            
            def set_keymap_celeste():
                KeymapConfig.KeymapMode.set_celeste()
                keymap.updateKeymap()
            
            def set_keymap_test():
                KeymapConfig.KeymapMode.set_test()
                keymap.updateKeymap()


            # Definitions of IME-ON/OFF functions. 

            def set_ime_on():
                keymap.wnd.setImeStatus(1)
    
            def set_ime_off():
                keymap.wnd.setImeStatus(0)


            # Definitions of functions combining Mode-change and IME-ON/OFF. 

            def set_keymap_limited_and_ime_on():
                set_keymap_limited()
                set_ime_on()

            def set_keymap_limited_and_ime_off():
                set_keymap_limited()
                set_ime_off()


            # set keymap_global 

            keymap_global["U1-c"]=set_keymap_cursor    # muhenkan - c
            keymap_global["U1-q"]=set_keymap_celeste   # muhenkan - q
            keymap_global["U1-t"]=set_keymap_test      # muhenkan - t
            keymap_global["U1-(28)"]=set_keymap_limited_and_ime_off     # muhenkan - henkan
            #keymap_celeste["U1-(240)"]=set_keymap_limited_and_ime_on   # muhenkan - hiragana (When IME is OFF) この設定はなくてもなぜか動作する。細かい仕様は調査が必要
            keymap_global["U1-(242)"]=set_keymap_limited_and_ime_on     # muhenkan - hiragana (When IME is ON?)
            keymap_global["U1-q"]=set_keymap_celeste                    # muhenkan - q

            keymap_global["S-(241)"]=set_keymap_limited_and_ime_on  #Shift - katakana/hiragana/romaji
            keymap_global["S-(28)"]=set_keymap_limited_and_ime_off  #Shift - henkan

            for any in ("", "S-", "C-", "C-S-", "A-", "A-S-", "A-C-", "A-C-S-", "W-", "W-S-", "W-C-", "W-C-S-", "W-A-", "W-A-S-", "W-A-C-", "W-A-C-S-"):
                keymap_global[any+"O-Slash"]=any+"Slash"    # oneshot Slash -> Slash

            
            
        @classmethod
        def _set_keymap_limited(cls, window_keymap):
            """This function set settings of `keymap_limited`. 
            - muhenkan + {key}
            
            Args:
                window_keymap (WindowKeymap): `keymap_limited`
            """

            window_keymap["A-z"]="A-Tab"
            window_keymap["A-S-z"]="A-S-Tab"
            window_keymap["RC-j"]="Enter"
            window_keymap["RC-h"]="Back"
            window_keymap["RC-d"]="Delete"
            for any in ("", "S-", "C-", "C-S-", "A-", "A-S-", "A-C-", "A-C-S-", "W-", "W-S-", "W-C-", "W-C-S-", "W-A-", "W-A-S-", "W-A-C-", "W-A-C-S-"):
                window_keymap[any+"U1-i"]=any+"Up"
                window_keymap[any+"U1-j"]=any+"Left"
                window_keymap[any+"U1-k"]=any+"Down"
                window_keymap[any+"U1-l"]=any+"Right"
                window_keymap[any+"U1-u"]=any+"PageUp"
                window_keymap[any+"U1-h"]=any+"Home"
                window_keymap[any+"U1-o"]=any+"PageDown"
                window_keymap[any+"U1-Semicolon"]=any+"End"
                window_keymap[any+"U1-n"]=any+"Enter"
                window_keymap[any+"U1-m"]=any+"Tab"

                # F-N -> FN
                for i in range(1,12+1):
                    window_keymap[any+"U1-"+str(i)]=any+"F"+str(i)
            
            

        @classmethod
        def _set_keymap_cursor(cls, window_keymap):
            """This function set settings of `keymap_cursor`. 
            - some function is available without "muhenkan" key.
            
            Args:
                window_keymap (WindowKeymap): `keymap_cursor`
            """
            window_keymap["A-z"]="A-Tab"
            window_keymap["A-S-z"]="A-S-Tab"
            window_keymap["RC-j"]="Enter"
            window_keymap["RC-h"]="Back"
            window_keymap["RC-d"]="Delete"            

            window_keymap["x"]="Delete"
            window_keymap["S-x"]="Back"
            window_keymap["w"]="C-Tab"
            window_keymap["q"]="C-S-Tab"
            window_keymap["O-f"]="LButton"
            window_keymap["O-g"]="RButton"
            
            for any in ("", "S-", "C-", "C-S-", "A-", "A-S-", "A-C-", "A-C-S-", "W-", "W-S-", "W-C-", "W-C-S-", "W-A-", "W-A-S-", "W-A-C-", "W-A-C-S-"):
                window_keymap[any+"i"]=any+"Up"
                window_keymap[any+"j"]=any+"Left"
                window_keymap[any+"k"]=any+"Down"
                window_keymap[any+"l"]=any+"Right"
                window_keymap[any+"u"]=any+"PageUp"
                window_keymap[any+"h"]=any+"Home"
                window_keymap[any+"o"]=any+"PageDown"
                window_keymap[any+"Semicolon"]=any+"End"
                window_keymap[any+"n"]=any+"Enter"
                window_keymap[any+"m"]=any+"Tab"



        @classmethod
        def _set_keymap_celeste(cls, window_keymap):
            """This function set settings of `keymap_cursor`. 
            - No function
            
            Args:
                window_keymap (WindowKeymap): `keymap_celeste`
            """
            pass


        @classmethod
        def _set_keymap_test(cls, windowkeymap,keymap):
            """テスト用キーマップモード
            現在はキーボードマクロのテストを実装している
            """
            
            
            # マクロテスト
            if 1:         
                
                """
                keymap を通して "abcde" と 0.5 sec おきに入力する関数
                この関数を直接キー入力に割り当てると意図したように動作しない

                現象としては実行中にキー入力が割り込む
                おそらく本関数のように実行に時間のかかる関数をキーに割り当てた場合、
                実行の終了以前にキー入力がなされる
                """
                def abcde_raw():
                    keymap.InputKeyCommand("a")()
                    time.sleep(0.5)
                    keymap.InputKeyCommand("b")()
                    time.sleep(0.5)
                    keymap.InputKeyCommand("c")()
                    time.sleep(0.5)
                    keymap.InputKeyCommand("d")()
                    time.sleep(0.5)
                    keymap.InputKeyCommand("e")()


                """
                keymap を通して "abcde" と 0.5 sec おきに入力する関数
                keymap.delayedCall(...) を使って呼ぶ
                
                ひとまず意図した動作を行う
                
                しかし、
                Time stamp inversion happened.
                のメッセージが表示される
                入力キーの up イベントが関数終了後に行われている
                
                """
                def abcde_delay(self):
                    keymap.delayedCall(abcde_raw,0)


                
                windowkeymap["U1-q"]=abcde_delay  # 意図したとおり動くが time stamp inversion のメッセージが出る
                # windowkeymap["U1-p"]=abcde_raw  # 意図したとおり動かない

            # デフォルト定義されているコマンドの置き換え
            if 1:
                # USER0-Up/Down/Left/Right : Move active window by 10 pixel unit
                windowkeymap[ "U1-Left"  ] = keymap.MoveWindowCommand( -10, 0 )
                windowkeymap[ "U1-Right" ] = keymap.MoveWindowCommand( +10, 0 )
                windowkeymap[ "U1-Up"    ] = keymap.MoveWindowCommand( 0, -10 )
                windowkeymap[ "U1-Down"  ] = keymap.MoveWindowCommand( 0, +10 )

                # USER0-Shift-Up/Down/Left/Right : Move active window by 1 pixel unit
                windowkeymap[ "U1-S-Left"  ] = keymap.MoveWindowCommand( -1, 0 )
                windowkeymap[ "U1-S-Right" ] = keymap.MoveWindowCommand( +1, 0 )
                windowkeymap[ "U1-S-Up"    ] = keymap.MoveWindowCommand( 0, -1 )
                windowkeymap[ "U1-S-Down"  ] = keymap.MoveWindowCommand( 0, +1 )

                # USER0-Ctrl-Up/Down/Left/Right : Move active window to screen edges
                windowkeymap[ "U1-C-Left"  ] = keymap.MoveWindowToMonitorEdgeCommand(0)
                windowkeymap[ "U1-C-Right" ] = keymap.MoveWindowToMonitorEdgeCommand(2)
                windowkeymap[ "U1-C-Up"    ] = keymap.MoveWindowToMonitorEdgeCommand(1)
                windowkeymap[ "U1-C-Down"  ] = keymap.MoveWindowToMonitorEdgeCommand(3)

                # Clipboard history related
                windowkeymap[ "C-S-Z"   ] = keymap.command_ClipboardList     # Open the clipboard history list
                windowkeymap[ "C-S-X"   ] = keymap.command_ClipboardRotate   # Move the most recent history to tail
                windowkeymap[ "C-S-A-X" ] = keymap.command_ClipboardRemove   # Remove the most recent history
                keymap.quote_mark = "> "                                    # Mark for quote pasting

                # Keyboard macro
                windowkeymap[ "U1-0" ] = keymap.command_RecordToggle
                windowkeymap[ "U1-1" ] = keymap.command_RecordStart
                windowkeymap[ "U1-2" ] = keymap.command_RecordStop
                windowkeymap[ "U1-3" ] = keymap.command_RecordPlay
                windowkeymap[ "U1-4" ] = keymap.command_RecordClear







    @classmethod
    def set_keymap(cls, keymap):

        # define modifier
        keymap.defineModifier(29,"User1")       #assign "muhenkan(無変換)" "User1"
        keymap.defineModifier("Slash","User2")  #assign "/" "User2"

        # Dynamic keymap configureation is realized by `checkfunc = {function to get current mode}`
        
        keymap_global=keymap.defineWindowKeymap()   
        cls.KeymapsImpl._set_keymap_global(keymap_global,keymap)

        keymap_limited = keymap.defineWindowKeymap(check_func=cls.KeymapMode.is_limited)
        cls.KeymapsImpl._set_keymap_limited(keymap_limited)

        keymap_cursor = keymap.defineWindowKeymap(check_func=cls.KeymapMode.is_cursor)
        cls.KeymapsImpl._set_keymap_cursor(keymap_cursor)

        keymap_celeste = keymap.defineWindowKeymap(check_func=cls.KeymapMode.is_celeste)
        cls.KeymapsImpl._set_keymap_celeste(keymap_celeste)

        keymap_test = keymap.defineWindowKeymap(check_func=cls.KeymapMode.is_test)
        cls.KeymapsImpl._set_keymap_test(keymap_test,keymap)




        







"""
自分用の設定
"""
def my_configure(keymap):
    KeymapConfig.set_keymap(keymap)
    



"""
設定
基本的には my_configure(keymap)だけ呼んであとはスキップする
デフォルト設定ファイルをできるだけ保存しておくためにこのようにしている
"""
def configure(keymap):

    # --------------------------------------------------------------------
    # Text editer setting for editting config.py file

    # Setting with program file path (Simple usage)
    if 1:
        keymap.editor = "C:\Program Files\Microsoft VS Code\Code.exe"

    # Setting with callable object (Advanced usage)
    if 0:
        def editor(path):
            shellExecute( None, "notepad.exe", '"%s"'% path, "" )
        keymap.editor = editor

    # --------------------------------------------------------------------
    # Customizing the display

    # Font
    keymap.setFont( "MS Gothic", 12 )

    # Theme
    keymap.setTheme("black")

    # --------------------------------------------------------------------

    # My definition
    if 1:   # limited mode and cursor mode (vim like) move with IJKL
        my_configure(keymap)

        
    # Original definitions 
    if 0:
        # Simple key replacement

        # User modifier key definition
        keymap.defineModifier( "CapsLock", "User0" )

        # Global keymap which affects any windows
        if 0:
            keymap_global = keymap.defineWindowKeymap()

            # USER0-Up/Down/Left/Right : Move active window by 10 pixel unit
            keymap_global[ "U0-Left"  ] = keymap.MoveWindowCommand( -10, 0 )
            keymap_global[ "U0-Right" ] = keymap.MoveWindowCommand( +10, 0 )
            keymap_global[ "U0-Up"    ] = keymap.MoveWindowCommand( 0, -10 )
            keymap_global[ "U0-Down"  ] = keymap.MoveWindowCommand( 0, +10 )

            # USER0-Shift-Up/Down/Left/Right : Move active window by 1 pixel unit
            keymap_global[ "U0-S-Left"  ] = keymap.MoveWindowCommand( -1, 0 )
            keymap_global[ "U0-S-Right" ] = keymap.MoveWindowCommand( +1, 0 )
            keymap_global[ "U0-S-Up"    ] = keymap.MoveWindowCommand( 0, -1 )
            keymap_global[ "U0-S-Down"  ] = keymap.MoveWindowCommand( 0, +1 )

            # USER0-Ctrl-Up/Down/Left/Right : Move active window to screen edges
            keymap_global[ "U0-C-Left"  ] = keymap.MoveWindowToMonitorEdgeCommand(0)
            keymap_global[ "U0-C-Right" ] = keymap.MoveWindowToMonitorEdgeCommand(2)
            keymap_global[ "U0-C-Up"    ] = keymap.MoveWindowToMonitorEdgeCommand(1)
            keymap_global[ "U0-C-Down"  ] = keymap.MoveWindowToMonitorEdgeCommand(3)

            # Clipboard history related
            keymap_global[ "C-S-Z"   ] = keymap.command_ClipboardList     # Open the clipboard history list
            keymap_global[ "C-S-X"   ] = keymap.command_ClipboardRotate   # Move the most recent history to tail
            keymap_global[ "C-S-A-X" ] = keymap.command_ClipboardRemove   # Remove the most recent history
            keymap.quote_mark = "> "                                      # Mark for quote pasting

            # Keyboard macro
            keymap_global[ "U0-0" ] = keymap.command_RecordToggle
            keymap_global[ "U0-1" ] = keymap.command_RecordStart
            keymap_global[ "U0-2" ] = keymap.command_RecordStop
            keymap_global[ "U0-3" ] = keymap.command_RecordPlay
            keymap_global[ "U0-4" ] = keymap.command_RecordClear


        # USER0-F1 : Test of launching application
        if 0:
            keymap_global[ "U0-F1" ] = keymap.ShellExecuteCommand( None, "notepad.exe", "", "" )


        # USER0-F2 : Test of sub thread execution using JobQueue/JobItem
        if 0:
            def command_JobTest():

                def jobTest(job_item):
                    shellExecute( None, "notepad.exe", "", "" )

                def jobTestFinished(job_item):
                    print( "Done." )

                job_item = JobItem( jobTest, jobTestFinished )
                JobQueue.defaultQueue().enqueue(job_item)

            keymap_global[ "U0-F2" ] = command_JobTest


        # Test of Cron (periodic sub thread procedure)
        if 0:
            def cronPing(cron_item):
                os.system( "ping -n 3 www.google.com" )

            cron_item = CronItem( cronPing, 3.0 )
            CronTable.defaultCronTable().add(cron_item)


        # USER0-F : Activation of specific window
        if 0:
            keymap_global[ "U0-F" ] = keymap.ActivateWindowCommand( "cfiler.exe", "CfilerWindowClass" )


        # USER0-E : Activate specific window or launch application if the window doesn't exist
        if 0:
            def command_ActivateOrExecuteNotepad():
                wnd = Window.find( "Notepad", None )
                if wnd:
                    if wnd.isMinimized():
                        wnd.restore()
                    wnd = wnd.getLastActivePopup()
                    wnd.setForeground()
                else:
                    executeFunc = keymap.ShellExecuteCommand( None, "notepad.exe", "", "" )
                    executeFunc()

            keymap_global[ "U0-E" ] = command_ActivateOrExecuteNotepad


        # Ctrl-Tab : Switching between console related windows
        if 0:

            def isConsoleWindow(wnd):
                if wnd.getClassName() in ("PuTTY","MinTTY","CkwWindowClass"):
                    return True
                return False

            keymap_console = keymap.defineWindowKeymap( check_func=isConsoleWindow )

            def command_SwitchConsole():

                root = pyauto.Window.getDesktop()
                last_console = None

                wnd = root.getFirstChild()
                while wnd:
                    if isConsoleWindow(wnd):
                        last_console = wnd
                    wnd = wnd.getNext()

                if last_console:
                    last_console.setForeground()

            keymap_console[ "C-TAB" ] = command_SwitchConsole


        # USER0-Space : Application launcher using custom list window
        if 0:
            def command_PopApplicationList():

                # If the list window is already opened, just close it
                if keymap.isListWindowOpened():
                    keymap.cancelListWindow()
                    return

                def popApplicationList():

                    applications = [
                        ( "Notepad", keymap.ShellExecuteCommand( None, "notepad.exe", "", "" ) ),
                        ( "Paint", keymap.ShellExecuteCommand( None, "mspaint.exe", "", "" ) ),
                    ]

                    websites = [
                        ( "Google", keymap.ShellExecuteCommand( None, "https://www.google.co.jp/", "", "" ) ),
                        ( "Facebook", keymap.ShellExecuteCommand( None, "https://www.facebook.com/", "", "" ) ),
                        ( "Twitter", keymap.ShellExecuteCommand( None, "https://twitter.com/", "", "" ) ),
                    ]

                    listers = [
                        ( "App",     cblister_FixedPhrase(applications) ),
                        ( "WebSite", cblister_FixedPhrase(websites) ),
                    ]

                    item, mod = keymap.popListWindow(listers)

                    if item:
                        item[1]()

                # Because the blocking procedure cannot be executed in the key-hook,
                # delayed-execute the procedure by delayedCall().
                keymap.delayedCall( popApplicationList, 0 )

            keymap_global[ "U0-Space" ] = command_PopApplicationList


        # USER0-Alt-Up/Down/Left/Right/Space/PageUp/PageDown : Virtul mouse operation by keyboard
        if 0:
            keymap_global[ "U0-A-Left"  ] = keymap.MouseMoveCommand(-10,0)
            keymap_global[ "U0-A-Right" ] = keymap.MouseMoveCommand(10,0)
            keymap_global[ "U0-A-Up"    ] = keymap.MouseMoveCommand(0,-10)
            keymap_global[ "U0-A-Down"  ] = keymap.MouseMoveCommand(0,10)
            keymap_global[ "D-U0-A-Space" ] = keymap.MouseButtonDownCommand('left')
            keymap_global[ "U-U0-A-Space" ] = keymap.MouseButtonUpCommand('left')
            keymap_global[ "U0-A-PageUp" ] = keymap.MouseWheelCommand(1.0)
            keymap_global[ "U0-A-PageDown" ] = keymap.MouseWheelCommand(-1.0)
            keymap_global[ "U0-A-Home" ] = keymap.MouseHorizontalWheelCommand(-1.0)
            keymap_global[ "U0-A-End" ] = keymap.MouseHorizontalWheelCommand(1.0)


        # Execute the System commands by sendMessage
        if 0:
            def close():
                wnd = keymap.getTopLevelWindow()
                wnd.sendMessage( WM_SYSCOMMAND, SC_CLOSE )

            def screenSaver():
                wnd = keymap.getTopLevelWindow()
                wnd.sendMessage( WM_SYSCOMMAND, SC_SCREENSAVE )

            keymap_global[ "U0-C" ] = close              # Close the window
            keymap_global[ "U0-S" ] = screenSaver        # Start the screen-saver


        # Test of text input
        if 0:
            keymap_global[ "U0-H" ] = keymap.InputTextCommand( "Hello / こんにちは" )


        # For Edit box, assigning Delete to C-D, etc
        if 0:
            keymap_edit = keymap.defineWindowKeymap( class_name="Edit" )

            keymap_edit[ "C-D" ] = "Delete"              # Delete
            keymap_edit[ "C-H" ] = "Back"                # Backspace
            keymap_edit[ "C-K" ] = "S-End","C-X"         # Removing following text


        # Customize Notepad as Emacs-ish
        # Because the keymap condition of keymap_edit overlaps with keymap_notepad,
        # both these two keymaps are applied in mixed manner.
        if 0:
            keymap_notepad = keymap.defineWindowKeymap( exe_name="notepad.exe", class_name="Edit" )

            # Define Ctrl-X as the first key of multi-stroke keys
            keymap_notepad[ "C-X" ] = keymap.defineMultiStrokeKeymap("C-X")

            keymap_notepad[ "C-P" ] = "Up"                  # Move cursor up
            keymap_notepad[ "C-N" ] = "Down"                # Move cursor down
            keymap_notepad[ "C-F" ] = "Right"               # Move cursor right
            keymap_notepad[ "C-B" ] = "Left"                # Move cursor left
            keymap_notepad[ "C-A" ] = "Home"                # Move to beginning of line
            keymap_notepad[ "C-E" ] = "End"                 # Move to end of line
            keymap_notepad[ "A-F" ] = "C-Right"             # Word right
            keymap_notepad[ "A-B" ] = "C-Left"              # Word left
            keymap_notepad[ "C-V" ] = "PageDown"            # Page down
            keymap_notepad[ "A-V" ] = "PageUp"              # page up
            keymap_notepad[ "A-Comma" ] = "C-Home"          # Beginning of the document
            keymap_notepad[ "A-Period" ] = "C-End"          # End of the document
            keymap_notepad[ "C-X" ][ "C-F" ] = "C-O"        # Open file
            keymap_notepad[ "C-X" ][ "C-S" ] = "C-S"        # Save
            keymap_notepad[ "C-X" ][ "C-W" ] = "A-F","A-A"  # Save as
            keymap_notepad[ "C-X" ][ "U" ] = "C-Z"          # Undo
            keymap_notepad[ "C-S" ] = "C-F"                 # Search
            keymap_notepad[ "A-X" ] = "C-G"                 # Jump to specified line number
            keymap_notepad[ "C-X" ][ "H" ] = "C-A"          # Select all
            keymap_notepad[ "C-W" ] = "C-X"                 # Cut
            keymap_notepad[ "A-W" ] = "C-C"                 # Copy
            keymap_notepad[ "C-Y" ] = "C-V"                 # Paste
            keymap_notepad[ "C-X" ][ "C-C" ] = "A-F4"       # Exit


        # Customizing clipboard history list
        if 1:
            # Enable clipboard monitoring hook (Default:Enabled)
            keymap.clipboard_history.enableHook(True)

            # Maximum number of clipboard history (Default:1000)
            keymap.clipboard_history.maxnum = 1000

            # Total maximum size of clipboard history (Default:10MB)
            keymap.clipboard_history.quota = 10*1024*1024

            # Fixed phrases
            fixed_items = [
                ( "name@server.net",     "name@server.net" ),
                ( "Address",             "San Francisco, CA 94128" ),
                ( "Phone number",        "03-4567-8901" ),
            ]

            # Return formatted date-time string
            def dateAndTime(fmt):
                def _dateAndTime():
                    return datetime.datetime.now().strftime(fmt)
                return _dateAndTime

            # Date-time
            datetime_items = [
                ( "YYYY/MM/DD HH:MM:SS",   dateAndTime("%Y/%m/%d %H:%M:%S") ),
                ( "YYYY/MM/DD",            dateAndTime("%Y/%m/%d") ),
                ( "HH:MM:SS",              dateAndTime("%H:%M:%S") ),
                ( "YYYYMMDD_HHMMSS",       dateAndTime("%Y%m%d_%H%M%S") ),
                ( "YYYYMMDD",              dateAndTime("%Y%m%d") ),
                ( "HHMMSS",                dateAndTime("%H%M%S") ),
            ]

            # Add quote mark to current clipboard contents
            def quoteClipboardText():
                s = getClipboardText()
                lines = s.splitlines(True)
                s = ""
                for line in lines:
                    s += keymap.quote_mark + line
                return s

            # Indent current clipboard contents
            def indentClipboardText():
                s = getClipboardText()
                lines = s.splitlines(True)
                s = ""
                for line in lines:
                    if line.lstrip():
                        line = " " * 4 + line
                    s += line
                return s

            # Unindent current clipboard contents
            def unindentClipboardText():
                s = getClipboardText()
                lines = s.splitlines(True)
                s = ""
                for line in lines:
                    for i in range(4+1):
                        if i>=len(line) : break
                        if line[i]=='\t':
                            i+=1
                            break
                        if line[i]!=' ':
                            break
                    s += line[i:]
                return s

            full_width_chars = "ａｂｃｄｅｆｇｈｉｊｋｌｍｎｏｐｑｒｓｔｕｖｗｘｙｚＡＢＣＤＥＦＧＨＩＪＫＬＭＮＯＰＱＲＳＴＵＶＷＸＹＺ！”＃＄％＆’（）＊＋，−．／：；＜＝＞？＠［￥］＾＿‘｛｜｝～０１２３４５６７８９　"
            half_width_chars = "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ!\"#$%&'()*+,-./:;<=>?@[\]^_`{|}～0123456789 "

            # Convert to half-with characters
            def toHalfWidthClipboardText():
                s = getClipboardText()
                s = s.translate(str.maketrans(full_width_chars,half_width_chars))
                return s

            # Convert to full-with characters
            def toFullWidthClipboardText():
                s = getClipboardText()
                s = s.translate(str.maketrans(half_width_chars,full_width_chars))
                return s

            # Save the clipboard contents as a file in Desktop directory
            def command_SaveClipboardToDesktop():

                text = getClipboardText()
                if not text: return

                # Convert to utf-8 / CR-LF
                utf8_bom = b"\xEF\xBB\xBF"
                text = text.replace("\r\n","\n")
                text = text.replace("\r","\n")
                text = text.replace("\n","\r\n")
                text = text.encode( encoding="utf-8" )

                # Save in Desktop directory
                fullpath = os.path.join( getDesktopPath(), datetime.datetime.now().strftime("clip_%Y%m%d_%H%M%S.txt") )
                fd = open( fullpath, "wb" )
                fd.write(utf8_bom)
                fd.write(text)
                fd.close()

                # Open by the text editor
                keymap.editTextFile(fullpath)

            # Menu item list
            other_items = [
                ( "Quote clipboard",            quoteClipboardText ),
                ( "Indent clipboard",           indentClipboardText ),
                ( "Unindent clipboard",         unindentClipboardText ),
                ( "",                           None ),
                ( "To Half-Width",              toHalfWidthClipboardText ),
                ( "To Full-Width",              toFullWidthClipboardText ),
                ( "",                           None ),
                ( "Save clipboard to Desktop",  command_SaveClipboardToDesktop ),
                ( "",                           None ),
                ( "Edit config.py",             keymap.command_EditConfig ),
                ( "Reload config.py",           keymap.command_ReloadConfig ),
            ]

            # Clipboard history list extensions
            keymap.cblisters += [
                ( "Fixed phrase", cblister_FixedPhrase(fixed_items) ),
                ( "Date-time", cblister_FixedPhrase(datetime_items) ),
                ( "Others", cblister_FixedPhrase(other_items) ),
            ]

